import Navbar from '@/components/Navbar';
import { Albert_Sans } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const albertsans = Albert_Sans();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Xurp Ia</title>
      </head>
      <body className={`${albertsans.className} bg-black`}>
        <Navbar />
        {children}
      </body>

    </html>
  )
}