import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Xurp Ia</title>
      </head>
      <body className='bg-[#011021]'>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}